params:
  seed: 42

  # environment wrapper clipping
  env:
    clip_actions: 1.0

  algo:
    name: amp_continuous

  model:
    name: continuous_amp
    # name: continuous_a2c_logstd

  network:
    name: amp
    # name: actor_critic
    # name: amp_with_SN
    fixed_lipschitz: True
    lipschitz_constant: 0.2

    separate: True
    space:
      continuous:
        mu_activation: None
        mu_init:
          name: default

        fixed_sigma: False
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0
          # val: -1.6 #(1/5)
        sigma_last:
          name: const_initializer
          val: -1.6 #(1/5)

    mlp:
      units: [512, 512]
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    disc:
      units: [256, 256]
      activation: relu

      initializer:
        name: default

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: TocabiAMPLower
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 9000
    save_best_after: 1000
    save_frequency: 1000
    grad_norm: 1.0
    entropy_coef: 0.001
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 32768
    mini_epochs: 6
    critic_coef: 5
    clip_value: False
    seq_length: 4
    bounds_loss_coef: 10

    amp_obs_demo_buffer_size: 200000
    amp_replay_buffer_size: 1000000
    amp_replay_keep_prob: 0.01
    amp_batch_size: 512
    amp_minibatch_size: 8384 #32768 #131072 # 4096*8
    disc_coef: 1 #5
    disc_logit_reg: 0.05
    disc_grad_penalty: 1 #5
    disc_reward_scale: 2
    disc_weight_decay: 0.0001
    normalize_amp_input: True

    task_reward_w: 0.7
    disc_reward_w: 0.3

    print_disc_prediction: True
    gan_type: lsgan # wgan, lsgan, gan
    lcp: True

    wandb: True
    wandb_project: 'tocabi_amp_walk'
    wandb_entity: 'john3-16'
    wandb_run_name: 'rl_games'
    wandb_tags: []
    wandb_group: ''
    wandb_logcode_dir: ''